### ISSUE TITLE
change display listing of history in Appdeamon app

### ISSUE THREAD

**Issue by Mariusthvdb** [azogue/eventsensor#11]
Hi Eugenio, 

sorry for this, I clicked the 'quote' button I think and this issue was created.... too quickly, since I wanted to ask you a eventsensor related question, about the Appdaemon app you created before. It is working beatifully, with 1 minor issue:

<img width="358" alt="Schermafbeelding 2020-04-30 om 10 02 35" src="https://user-images.githubusercontent.com/33354141/80687241-4b535200-8aca-11ea-83ce-4e2e3fe9b581.png">

Could it be listing the history 10 at the bottom? Preferably without adding a leading 0 to history 1-9. Like the original 'variable' solution I used:

<img width="365" alt="Schermafbeelding 2020-04-30 om 10 07 46" src="https://user-images.githubusercontent.com/33354141/80687348-75a50f80-8aca-11ea-9e90-f8358a10bff5.png">

Thanks if you can find a moment to check, and again sorry for creating this issue here in this repo...

cheers,
Marius

cc @Mariusthvdb 

> If you have would have another spare moment, might I kindly ask you to have a look at this,

Too much Marius, don't overdo it. With what I showed to you I think it is sufficient, you should be capable of continuing from it. Also, big off-topic here.

_Originally posted by @azogue in https://github.com/azogue/eventsensor/issues/2#issuecomment-617921417_

**Comment by azogue** [comment]
> since I wanted to ask you a eventsensor related question, about the Appdaemon app you created before. 

As they are not related at all, I'm closing this. The appdaemon code you're talking about lives in another repo, open the issue there, please
