### ISSUE TITLE
Better filter for event_data

### ISSUE THREAD

**Issue by Fabenissimo** [azogue/eventsensor#13]
Hi,

I'm trying to create binary sensors from events that I receive from my cameras.

I get these events from my camera:

```
{
    "event_type": "netatmo_event",
    "data": {
        "type": "movement",
        "data": {
            "user_id": "x",
            "snapshot_id": "x",
            "snapshot_key": "x",
            "snapshot_url": "x",
            "event_type": "movement",
            "camera_id": "ma:ca:dr:es:sx:xx",
            "device_id": "ma:ca:dr:es:sx:xx",
            "home_id": "x",
            "home_name": "x",
            "event_id": "x",
            "message": "Bewegung von Camera Treppenhaus erkannt",
            "push_type": "NACamera-movement"
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-07-25T09:12:49.580668+00:00",
    "context": {
        "id": "x",
        "parent_id": null,
        "user_id": null
    }
}
```

I try to make a event-sensor instance from each possible combination. So I have a indoor and outdoor camera, both use the pair ```"type": "movement"``` for example. So If I want to create a event sensor for each movement event for each camera I'd tried to do it like this:

![image](https://user-images.githubusercontent.com/46358139/88453773-78fe2c00-ce6a-11ea-85b0-d77ad6202411.png)

But If I do it like shown above the sensor never get's a state, I guess it's because the second event_data (```data: {push_type: NACamera-movement}```) is only searching for an exact key. So If there's more key/value pairs inside the specified key it's no exact match and therefore the eventsensor doesn't trigger to update, right?

If I remove the second event_data value, the sensor triggers, but then it's not possible for me to seperate the events from Camera A to Camera B as the both produce the same ```"type": "movement"```.

It's a similar issue for person-events from my camera. Inside the event -data field I get the value ```known_face``` but I can't filter it because its inside another nested value with more than one value inside that nesting.

Do you think it would be possible for you to implement a feature that would allow to filter out a specific key/value pair inside another key/value pair and ignore the other pairs? (e.g. Option "Fully match event_data" or "Partial match event_data")

Also unrelated to the above question, is it possible to filter out value paris with a mac_adress as the value via the UI?
I've seen in your readme that you can do it in yaml. What would I have to do in the UI to achieve the same thing? Put the mac-adress into "" so it ignores the ":" between the mac-adress pairs?

So wold it look like this?
```device_id: "ma:ca:dr:es:sx:xx"```
or this?
```device_id: ma:ca:dr:es:sx:xx```

**Comment by azogue** [comment]
Hi @Fabenissimo,

About this:

> Also unrelated to the above question, is it possible to filter out value paris with a mac_adress as the value via the UI?
I've seen in your readme that you can do it in yaml. What would I have to do in the UI to achieve the same thing? Put the mac-adress into "" so it ignores the ":" between the mac-adress pairs?
> 
> So wold it look like this?
> device_id: "ma:ca:dr:es:sx:xx"
> or this?
> device_id: ma:ca:dr:es:sx:xx

The second one :)

It is parsing the key: value pairs with `key, value = pair.split(":", maxsplit=1)`, so it only _sees_ the first ":". Do not use " there.

**Comment by azogue** [comment]
About the first one, it is one of the things I've got in the "to do list". In fact, there is a literal `# TODO make better filter looking at sub-nested data` in the code right now... but I don't know when I'll have some time to implement that (pull requests are appreciated!)

**Comment by azogue** [comment]
Hi @Fabenissimo, it was easier than I thought 👍 

It is done in #15, so I'm closing this issue. I'll publish a new version for HACS very soon :)

**Comment by Fabenissimo** [comment]
Thank you so much! Can't wait to get my hands on it :-)

**Comment by Fabenissimo** [comment]
Hi @azogue ,

I had some time now to play around with it. I've got one example that I can't get to work:

I get this event:
```
{
    "event_type": "netatmo_event",
    "data": {
        "type": "person",
        "data": {
            "user_id": "x",
            "persons": [
                {
                    "id": "x",
                    "face_id": "x",
                    "face_key": "x",
                    "is_known": true,
                    "face_url": "x"
                }
            ],
            "snapshot_id": "x",
            "snapshot_key": "x",
            "snapshot_url": "x",
            "event_type": "person",
            "camera_id": "x",
            "device_id": "x",
            "home_id": "x",
            "home_name": "x",
            "event_id": "x",
            "message": "Fabian von Camera Treppenhaus gesehen",
            "push_type": "NACamera-person",
            "id": "x",
            "name": "Fabian",
            "is_known": true,
            "face_url": "x"
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-07T08:09:49.610627+00:00",
    "context": {
        "id": "x",
        "parent_id": null,
        "user_id": null
    }
}
```

And I've got this event sensor setup:
![image](https://user-images.githubusercontent.com/46358139/89624838-245da680-d897-11ea-8d62-8c1af90f7e3a.png)

For some reason, I can't get the sensor to fire once I add the ```data.is_known: true``` to the event filter. Without it it works fine, but as soon as I add the above filter (data.is_known: true) to the other filters the sensor doesn't fire anymore.
