### ISSUE TITLE
Would it be possible to have certain states clear "immediately"? 

### ISSUE THREAD

**Issue by vegardengen** [azogue/eventsensor#14]
Using eventsensor, I am not able to use the same button press for repeated action, so I have fallen back to listening to events for my short-click detection.

But once a button-release have fired an event, is it really useful to *keep* the state, that this button was what was clicked last?

I, at least, feel it is more useful to be able to get the same button release (and short click) again.

I have not really thought this through. I guess I'd like to get the state that a button is still pressed - i.e. that a 2000/2001 has been fired, and no 2003 yet, if we are thinking about hue dimmers.

Currently, I am using eventsensor logic to detect long presses (for continuous dimming), and raw event listening to detect short clicks - because then I can detect multiple clicks.

**Comment by azogue** [comment]
Hi @vegardengen,

For triggering automations, the preferred method is to directly use **device triggers** for each kind of remote press, as it is much easier to define those than an **event trigger** (but in essence, they're the same thing).

The last approach, and usually the more complex one, is to use **state triggers** (using the state of these event sensors).
For a state trigger to work with repeated presses, you need to define the trigger without the `to:` constrain (nor the `from:` one), so it fires for all state changes, and then use a `condition:` to filter only the button press you want.

In the end, this CC only serves to store a state with the last button press, but it's not the best approach for automations: it can be done, but with care :)

**Comment by azogue** [comment]
I'm closing this issue, as it is related to automation definitions better solved without this custom integration, or to implement a behavior which is the opposite of the main objective of this sensor (which is to persist an event!)

**Comment by clarkd** [comment]
> For triggering automations, the preferred method is to directly use device triggers for each kind of remote press, as it is much easier to define those than an event trigger (but in essence, they're the same thing).

@azogue I don't see any device triggers added for my hue buttons, is the only option to use the state trigger as you described?

**Comment by azogue** [comment]
Hi @clarkd,

> I don't see any device triggers added for my hue buttons, 

<img width="793" alt="Captura de pantalla 2020-08-03 a las 21 16 24" src="https://user-images.githubusercontent.com/9748301/89218575-994a8b00-d5ce-11ea-8368-1b9da95f1352.png">

These are in the devices list of the integration you're using to connect with them (hue /deconz/zha) -> Configuration->Integrations->XXX->Remote name.

**Are you using common Hue Dimmer Switches or another kind of remote?** (maybe they are not implemented in HA as device triggers)

Anyway,

> is the only option to use the state trigger as you described?

No, as I described 3 options :)

1. Device trigger
2. Event trigger (there is ALWAYS an event)
3. State trigger with eventsensor

**Comment by azogue** [comment]
Hi again @clarkd, I just saw https://github.com/home-assistant/core/issues/38511 :(

If you post the event data those Hue smart buttons are generating, I could **implement a state mapping template** for them here in eventsensor, and also make a **PR in HA Core to implement device triggers** for them, what do you say? 

(or you could do that yourself if you want, feel free to cc me for review if you do that)

Here in eventsensor defining a new kind of sensor is just basically to create something like this:

```python
PRESET_HUE_TAP = "Hue Tap Switch"
PRESET_HUE_TAP_MAPPING = {
    34: "1_click",
    16: "2_click",
    17: "3_click",
    18: "4_click",
}
```

and in HA Core is a little bit more complex, but also easy as the path is already created for other sensors:

```python
HUE_TAP_REMOTE_MODEL = "Hue tap switch"  # ZGPSWITCH
HUE_TAP_REMOTE = {
    (CONF_SHORT_PRESS, CONF_BUTTON_1): {CONF_EVENT: 34},
    (CONF_SHORT_PRESS, CONF_BUTTON_2): {CONF_EVENT: 16},
    (CONF_SHORT_PRESS, CONF_BUTTON_3): {CONF_EVENT: 17},
    (CONF_SHORT_PRESS, CONF_BUTTON_4): {CONF_EVENT: 18},
}
```

**Comment by clarkd** [comment]
Hi @azogue - thanks for this, that looks promising!

I managed to get the buttons working with eventsensor using the same config mapping as the Dimmer Switch - it looks to just use the 100* events, i.e. the same that are triggered for the first button on the dimmer switch. e.g. 1002 = short click, 1003 = long click. 

I've just created the PR into eventsensor (added you as reviewer), let me know if there's anything I missed out. I'll do the same for the core shortly - thanks for the guidance!

**Comment by clarkd** [comment]
@azogue Core PR raised (home-assistant/core#38555) - one thing I wasn't sure about was the value for the `HUE_BUTTON_REMOTE_MODEL` prop but I've added the button name, let me know your thoughts... Additionally, I'm not setup to run the tests locally (have just made the file changes) so might need some help there...!

**Comment by azogue** [comment]
@clarkd you need to follow the environment setup which is in the dev docs: https://developers.home-assistant.io/docs/development_environment

After that, you should be capable not only of running the test suite, but also the pre-commit hooks, to reformat code and check all kind of _disturbances in the code_ :) (like an unsorted import, for example)

Running tests locally is a requirement for all PRs to Core, btw. Also, maybe some unit test is required in the PR, so anyway is worth an environment setup :)

**Comment by clarkd** [comment]
> @clarkd you need to follow the environment setup which is in the dev docs: https://developers.home-assistant.io/docs/development_environment
> 
> After that, you should be capable not only of running the test suite, but also the pre-commit hooks, to reformat code and check all kind of _disturbances in the code_ :) (like an unsorted import, for example)
> 
> Running tests locally is a requirement for all PRs to Core, btw. Also, maybe some unit test is required in the PR, so anyway is worth an environment setup :)

Awesome, I've got the devcontainer installed and it's working well. Fixed up the remaining issues, but I still haven't been able to run the tests. When I try to run `tox`, the command isn't found - otherwise the container is working as expected, can access HA, run black etc etc. Any ideas? I'm on Windows with VSC.

**Comment by clarkd** [comment]
Ignore me... I was missing the venv activate step - doh! Tests running 👍
