### ISSUE TITLE
How do you start the wizard?

### ISSUE THREAD

**Issue by K-RAD** [azogue/eventsensor#20]
I do not see any option anywhere to start the wizard to create a sensor. What am I missing?

![image](https://user-images.githubusercontent.com/3822874/97934662-9a7a8800-1d76-11eb-86a9-0b1d55f85ad2.png)

**Comment by zaggo** [comment]
+1 
Same here

**Comment by oneseventhree** [comment]
It's in integations > then search eventsensor

**Comment by K-RAD** [comment]
Doesn't show up in my integrations list

![image](https://user-images.githubusercontent.com/3822874/99645920-1ef42880-2a50-11eb-92a0-148598304b87.png)

**Comment by oneseventhree** [comment]
Very strange. It should look like this:

<img width="814" alt="Screen Shot 2020-11-22 at 10 49 01 am" src="https://user-images.githubusercontent.com/15043282/99890146-5fea7800-2cb0-11eb-80c4-efc610ed9ef2.png">

**Comment by mariojg25** [comment]
I have the same problem as @K-RAD 
I installed the integration through HACS and then I restarted HA, just like in the documentation. Now I cannot see the integration as described

**Comment by K-RAD** [comment]
I tried it again and for me it works, now I can find it in the integrations. Maybe it just took a bunch of restarts

**Comment by mariojg25** [comment]
I will keep trying, thanks @K-RAD

**Comment by estiens** [comment]
I also have tried installing and reinstalling(and restarting a bunch of times) with no luck seeing it in integrations menu. Will try full reboot of hass

**Comment by estiens** [comment]
(full restart of supervisor works for it to show up in integrations for me)

**Comment by azogue** [comment]
Hi there, 

> I also have tried installing and reinstalling(and restarting a bunch of times) with no luck seeing it in integrations menu

I think it is a **browser cache issue**, not related to HA Core directly, or to this specific custom component.

Only a 1st restart should be needed to make it work after installing it from HACS. 
If it doesn't show after that one restart, maybe clearing the browser cache (or just update the page with CMD+R a few times) should do the trick
