### ISSUE TITLE
Integration 'eventsensor' not found.

### ISSUE THREAD

**Issue by akeslo** [azogue/eventsensor#30]
After upgrading to v2.4.0 I am seeing the below error in my logs:

Platform error: sensor - Integration 'eventsensor' not found.
2:04:46 PM – config.py (ERROR)
Setup failed for eventsensor: Integration not found.
2:04:45 PM – setup.py (ERROR)

**Comment by kadiusone** [comment]
I have the same issue. I tried also downgrade v2.2 but still integration not found
![image](https://user-images.githubusercontent.com/52676677/110219075-5c74a880-7ebd-11eb-8526-0b561893ab76.png)

**Comment by akeslo** [comment]
@kadiusone You are right, same behavior on my end via HACS.  Manually uploading was the fix, folder is missing from custom_components.  Thanks!

**Comment by Kugelfang666** [comment]
same problem for me, manually downloading from git and putting into the custom_component folder fixed it for me

**Comment by azogue** [comment]
Hi there 👋

Yesterday I tried to fix some minor things and I ended by breaking the CC completely with v2.4.0... Sorry about that 🥺

It should be working again in HACS with v2.4.1
