### ISSUE TITLE
Access the wizard configuration

### ISSUE THREAD

**Issue by Djaiff** [azogue/eventsensor#35]
Hi, thanks for this amazing integration. I've just installed it but I don't know how to access the wizard configuration. 
I go to HACS>Integrations then I see "Event Sensor" but I don't know how to trigger the wizard configuration.
Could you please give me some more details ?
Thanks in advance
Jeff

**Comment by azogue** [comment]
Hi @Djaiff, 

> I go to HACS>Integrations then I see "Event Sensor" but I don't know how to trigger the wizard configuration.

HACS is to install (and therefore **make available**) custom integrations and other custom things. 

After the custom integrations are installed (-> they appear as subfolders on `config/custom_components`), and HA Core has restarted, then **they are available in the same place of the _Core_ integrations**: Configuration->Integrations.
From there, add a new integration and search for "EventSensor" there:

<img width="299" alt="step1-integrations-add-button" src="https://user-images.githubusercontent.com/9748301/119253604-48823e00-bbb2-11eb-9c22-a431655bf9e3.png">

<img width="601" alt="step2-integrations-select-EventSensor" src="https://user-images.githubusercontent.com/9748301/119253605-5041e280-bbb2-11eb-9892-2f152a837b5c.png">

<img width="676" alt="step3-integrations-start-wizard" src="https://user-images.githubusercontent.com/9748301/119253608-5637c380-bbb2-11eb-8efc-f73c1ff4804d.png">

Note: if the newly installed custom integration does not appear in the Integrations menu, **clear you browser cache**, and it should appear after that.

**Comment by Djaiff** [comment]
Thank you for your detailed answer ! Actually, I closed the issue since I already managed to add the "EventSensor" using the manual configuration. After that, I saw the integration appear as you explained.
