### ISSUE TITLE
bad_state on sensor

### ISSUE THREAD

**Issue by oneseventhree** [azogue/eventsensor#40]
Hi,

My hue switch works with automations but I can't get it to show the state in UI and instead shows "bad_state":
![image](https://user-images.githubusercontent.com/15043282/147012539-438f3128-31cf-4d7e-b7f4-90c5c2b21f6d.png)

This is the event:
![image](https://user-images.githubusercontent.com/15043282/147012514-dc690476-1a4a-4dc6-888a-fa2a4a521066.png)

It is set up with V1 dimmer switch:
![image](https://user-images.githubusercontent.com/15043282/147012597-c7d25db0-423c-4075-87ab-769c1dd63007.png)

I have some hue switches in deconz that works perfectly with EventSensor but I can't get this to work.

Thanks in advance

**Comment by azogue** [comment]
Hi @oneseventhree, 

The Hue integration changed to use the new v2 API, and with that, the event data from remotes also changed, making the old EventSensor incompatible :(

Check the [new release v3.0.0](https://github.com/azogue/eventsensor/releases/tag/v3.0.0) (with changes in https://github.com/azogue/eventsensor/pull/39), to address these changes and reconfigure those sensors to compose the state with the `type,subtype` event data keys 🍻

**Comment by oneseventhree** [comment]
> Hi @oneseventhree,
> 
> The Hue integration changed to use the new v2 API, and with that, the event data from remotes also changed, making the old EventSensor incompatible :(
> 
> Check the [new release v3.0.0](https://github.com/azogue/eventsensor/releases/tag/v3.0.0) (with changes in #39), to address these changes and reconfigure those sensors to compose the state with the `type,subtype` event data keys 🍻

Hi @azogue thanks for the reply! 

I have 3.0.0

Is there a document that has something I can copy and paste to overwrite:

1000: click, 1001: hold, 1002: click_up, 1003: hold_up, 1004: 2_click, 1005: 3_click, 1006: 4_click, 1010: 5_click

Sorry I am a bit new to this so I don't know what you mean by type,subtype

**Comment by azogue** [comment]
Hi @oneseventhree,

The **"Event field to use as sensor state"** is not "event" anymore for Hue v2 (that key doesn't exist). 

Now the button combination comes with 2 new event data fields: "type" and "subtype". The old version didn't work because the "Event field to use as sensor state" had to be a single key, so the change was to be able to combine keys to generate a sensor state from more than 1 event key.

--> so instead of "event", now the state comes from the **"type,subtype"** keys, to produce states like "short_release-1" or "initial_press-2".

For the _new sensor wizard_, these new configurations are also implemented, and there are new state mappings for the dimmer switch and the smart button (I don't have a Tap linked to the Hue bridge, so I wasn't sure of its new states)

**Comment by oneseventhree** [comment]
> Hi @oneseventhree,
> 
> The **"Event field to use as sensor state"** is not "event" anymore for Hue v2 (that key doesn't exist).
> 
> Now the button combination comes with 2 new event data fields: "type" and "subtype". The old version didn't work because the "Event field to use as sensor state" had to be a single key, so the change was to be able to combine keys to generate a sensor state from more than 1 event key.
> 
> --> so instead of "event", now the state comes from the **"type,subtype"** keys, to produce states like "short_release-1" or "initial_press-2".
> 
> For the _new sensor wizard_, these new configurations are also implemented, and there are new state mappings for the dimmer switch and the smart button (I don't have a Tap linked to the Hue bridge, so I wasn't sure of its new states)

Thank you!

For anyone else this is what needs to be done:

Hue Dimmer Switch:
![image](https://user-images.githubusercontent.com/15043282/147226027-fafd2a89-df73-4a1c-b3e5-b2a003769b90.png)


Tap Switch:
![image](https://user-images.githubusercontent.com/15043282/147226147-9b314a10-f7b3-4d2e-85ae-3f20c580a237.png)
