### ISSUE TITLE
Issue reading numeric values in event filter

### ISSUE THREAD

**Issue by odechr** [azogue/eventsensor#43]
Hi,

Im not sure if it is the integration or me that doesnt understand the event filter.
Filtering out the codes and display them as different values works fine.
But when i try to filter the "message: "X" for each sensor it doesnt work anymore.

"Message: 1 " is the ID of the sensor. and i have a bunch.

```
Event 2 fired 12:45 PM:
{
    "event_type": "sia_event_8124_ABCDEF",
    "data": {
        "message_type": "SIA-DCS",
        "receiver": null,
        "line": "L0",
        "account": "ABCDEF",
        "sequence": "0992",
        "content": "#ABCDEF|Nri1/BR1]_11:45:27,01-07-2022",
        "ti": null,
        "id": null,
        "ri": "1",
        "code": "BR",
        "message": "1",
        "x_data": null,
        "timestamp": "2022-01-07T11:45:27+00:00",
        "event_qualifier": null,
        "event_type": null,
        "partition": null,
        "extended_data": null,
        "sia_code": {
            "code": "BR",
            "type": "Burglary Restoral",
            "description": "Alarm/trouble condition has been eliminated",
            "concerns": "Zone or point"
        }
    },
    "origin": "LOCAL",
    "time_fired": "2022-01-07T11:45:29.833008+00:00",
    "context": {
        "id": "325a2af2e6a4e6d5eb68178620b50dac",
        "parent_id": null,
        "user_id": null
    }
}
```

```
Event 2 fired 12:45 PM:
{
    "event_type": "sia_event_8124_ABCDEF",
    "data": {
        "message_type": "SIA-DCS",
        "receiver": null,
        "line": "L0",
        "account": "ABCDEF",
        "sequence": "0992",
        "content": "#ABCDEF|Nri1/BR1]_11:45:27,01-07-2022",
        "ti": null,
        "id": null,
        "ri": "1",
        "code": "BR",
        "message": "1",
        "x_data": null,
        "timestamp": "2022-01-07T11:45:27+00:00",
        "event_qualifier": null,
        "event_type": null,
        "partition": null,
        "extended_data": null,
        "sia_code": {
            "code": "BR",
            "type": "Burglary Restoral",
            "description": "Alarm/trouble condition has been eliminated",
            "concerns": "Zone or point"
        }
    },
    "origin": "LOCAL",
    "time_fired": "2022-01-07T11:45:29.833008+00:00",
    "context": {
        "id": "325a2af2e6a4e6d5eb68178620b50dac",
        "parent_id": null,
        "user_id": null
    }
}
```

This doesnt work, i need to filter the sensor from the message. Message is like the sensor ID.
![image](https://user-images.githubusercontent.com/57597773/148540988-752cfe84-9f92-4614-9320-6add697663af.png)

THis does work, but will not filter on this spesific sensor:
![image](https://user-images.githubusercontent.com/57597773/148541070-b50db466-95a6-4640-bf70-715bed1ff51f.png)

**Comment by odechr** [comment]
So it looks like it has issue with numbers..
message: 1 <- doesnt work
code: br <- This works, then it only changes state if BR is in the event.

Anyone would know how to make it read numbers?

**Comment by azogue** [comment]
> So it looks like it has issue with numbers.. message: 1 <- doesnt work code: br <- This works, then it only changes state if BR is in the event.
> 
> Anyone would know how to make it read numbers?

Hi @odechr, sorry for the late answer 😔, didn't see the issue 🙈

The internal parser is **trying to recognize numbers** (integers and floats) from the text input in the config wizard, so that `message: 1` is **stored as a number**, and then the filter fails because **the event has a string, not a number**, which is not the usual scenario (`"1"`)

💡 **Have you tried to define `message: "1"`?** (with the quotes!)

I think that should work ok 👌
