### ISSUE TITLE
Improvement: bundle items in one integration in GUI

### ISSUE THREAD

**Issue by Kugelfang666** [azogue/eventsensor#5]
I really like this CC! Great job! 

I run a setup with 15 Hue dimmers. Hence, the integration menus in the GUI becomes quite crowded since every dimmer in showing up as an individual integration. It would be so cool if there could be one integration event sensor which features multiple items (all the actual switches...)

**Comment by azogue** [comment]
Hi @Kugelfang666 

I didn't found any tool (or other integration as an example) for a system to **add/remove/edit** individual items (:= event sensors) from a unique `config_entry`.

Without that, configuring all entities at once would be messy and uncomfortable.

For integrations that **support some kind of discovery system**, that is the best approach, as the setup configures all devices/entities and then the user can disable/enable them individually but **that is not the case here**, as we just listen to events.

If you have some suggestion of how to approach that UI problem I promise I'll give it a look :)

Also, if you discover any integration **editing yaml** in a field in the config flow, ping me.

**Comment by azogue** [comment]
Closing this after it's resolved on HA Core, integrations view on HA >= 0.110 looks great :)
