### ISSUE TITLE
Hue Tap Switch - Zigbee2MQTT

### ISSUE THREAD

**Issue by oneseventhree** [azogue/eventsensor#50]
Hi,

Rcently changed over to Z2M and was wondering how I can get it to work with the tap switch.

Here is what I have currently:
<img width="592" alt="Screenshot 2022-12-28 at 1 36 15 pm" src="https://user-images.githubusercontent.com/15043282/209748443-f4595c37-b15a-4ae2-8343-561b7c97988b.png">

Here is what HA see's when I listen:

<img width="919" alt="Screenshot 2022-12-28 at 1 08 23 pm" src="https://user-images.githubusercontent.com/15043282/209748489-767ac065-2654-44a2-b5af-64de6492c96e.png">

It's basically just:
```
event_type: state_changed
data:
  entity_id: sensor.living_ room tap_switch_action
  old state:
    entity_id: sensor. living_room_tap_switch_action
    state: press 1 attributes:
```

**Comment by azogue** [comment]
Hi @oneseventhree, **this event sensor cannot link to the 'state_changed' event**. It's an explicit limitation in https://github.com/azogue/eventsensor/blob/dddff4a994e69d5f3fa67a86031d07fcdf84fc1b/custom_components/eventsensor/sensor.py#L60

When any HA entity changes state, **including this sensor**, a 'state_changed' event is emitted. So, apart from the _magnitude_ problem (there are too many state-changed events), there is also a potential infinite loop problem, as the sensor would trigger after its state change AGAIN and again.

As I understand, with Z2M, you already have 'states' for the switches, right? so you don't need to listen to _events_, just _reformat_ some entities to show attributes as states, isn't it?

Closing this one 👍
