### ISSUE TITLE
Eventsensor cannot be added in GUI Integration

### ISSUE THREAD

**Issue by Kilowatt-W** [azogue/eventsensor#54]
Hello all together,

Referencing to Issue 12 (dont know if a closed issue gets notified on new comments : [https://github.com/azogue/eventsensor/issues/12](url)

at the moment it looks like the option to add an eventsenor as intergration in the gui disappeared again.

There is just the option to add by manufacturer and eventsensor is never showing up.

Is it possible that there is an other name used ?

My Versions :

Home Assistant 2023.4.5
Supervisor 2023.04.0
Operating System 10.0
Frontend 20230411.1 - latest

Eventsensor : 3.01 latest reinstalled but no change

Greetings from Austria,

Kilowatt

**Comment by johntdyer** [comment]
Same issue here

**Comment by jordy101091** [comment]
Same issue for me, eventSensor is now longer found when adding through the GUI

**Comment by Tofty85** [comment]
Same issue here, tried clearing browser cache and rolling back event sensor versions with no luck, all my existing hue/ Ikea remotes still working configured through event sensor integration, HA still showing Hue Dimmers etc... related to event sensor integration but not showing in Devices/Services in GUI

**Comment by blizzrdof77** [comment]
Also experiencing this issue. It works via manual YAML configuration, but doesn’t show up in the Home Assistant GUI. I’ve attached a screenshot.
![IMG_7107](https://user-images.githubusercontent.com/890252/236933301-47d6a58a-62ac-41c2-833c-5108592081bd.png)

**Comment by azogue** [comment]
Thanks for reporting! sorry I didn't see it before 😢

I think I have it fixed in #55, I'll publish a new release for HACS soon 👍
