### ISSUE TITLE
Issue with 2023.8.

### ISSUE THREAD

**Issue by collateral87** [azogue/eventsensor#59]
Since upgrading to 2023.8. this awsome Integration doesnt load on startup.

![Screenshot_20230802_210755_Home Assistant.jpg](https://github.com/azogue/eventsensor/assets/97076257/1ce293ef-98b1-4745-851f-4c9fa3fb0e26)

**Comment by klatka** [comment]
+1

**Comment by wwwescape** [comment]
+1. Getting the same issue.

**Comment by robertwigley** [comment]
Was just coming to log the same.

**Comment by skybox99** [comment]
+1

**Comment by stehliner** [comment]
2023.8 has a new build-in integration for events: [https://www.home-assistant.io/integrations/event](url) 
I just changed my hue dimmer switch automation to this one and it worked well

**Comment by robertwigley** [comment]
> 2023.8 has a new build-in integration for events

Yes, but that's only any good if the integration provides support for it and it doesn't allow you to build your own event sensors.
